import React, { useEffect, useState } from 'react';
import type { Metadata } from 'next';
import { ReCaptchaProvider } from 'next-recaptcha-v3';
import NavBar from '../../components/navbar';
import Header from '../../components/contacts/header';
import ContactForm from '../../components/contacts/contactForm';

export const metadata: Metadata = {
  title: 'Contact page',
  description: 'Generated by create next app',
};

const Contacts = () => (
  <ReCaptchaProvider
    language="en"
    reCaptchaKey="6LedHpUpAAAAAIZKtDmFDmjkSkOKJJbTmuTPRq8C"
  >
    <main>
      <nav className="relative z-10">
        <NavBar
          items={[
            { text: 'Projects', href: '/#projects' },
            { text: 'Approach', href: '/#approach' },
            { text: 'Expertise', href: '/#expertise' },
            { text: 'Contacts', href: '/#contacts' },
          ]}
        />
      </nav>
      <header>
        <Header>
          let&apos;s work
          <br />
          together
        </Header>
      </header>
      <section>
        <ContactForm />
      </section>
    </main>
  </ReCaptchaProvider>
);

export default Contacts;
