import React from 'react';
import type { Metadata } from 'next';
import NavBar from '../../components/navbar';
import Header from '../../components/contacts/header';
import ContactForm from '../../components/contacts/contactForm';

export const metadata: Metadata = {
  title: 'Contact page',
  description: 'Generated by create next app',
};

const Contacts = () => (
  <main>
    <nav className="relative z-10">
      <NavBar
        items={[
          { text: 'Projects', href: '/#projects' },
          { text: 'Approach', href: '/#approach' },
          { text: 'Expertise', href: '/#expertise' },
          { text: 'Contacts', href: '/#contacts' },
        ]}
      />
    </nav>
    <header>
      <Header>
        let&apos;s work
        <br />
        together
      </Header>
    </header>
    <section>
      <ContactForm />
    </section>
  </main>
);

export default Contacts;
