
FROM node:20.8 as build

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm i

COPY . .

RUN npm run build

FROM nginx:latest

COPY docker/prod/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/out/ /etc/nginx/html

EXPOSE 80

