services:
 app:
   build:
     dockerfile: ./docker/dockerfile
     context: .
   ports:
     - 3000:3000
   environment:
     - SERVER_PORT=8080
     - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/notes
   volumes:
     - ./:/app
   command: npm run dev