
FROM node:20.8

WORKDIR /app

ENV NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY = ${NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY}
ENV NEXT_PUBLIC_GOOGLE_RECAPTCHA_SECRET_KEY = ${NEXT_PUBLIC_GOOGLE_RECAPTCHA_SECRET_KEY}

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm i

COPY . .

CMD [ "npm", "dev" ]